language: c
os: Linux
compiler: gcc

env:
  global:
   - secure: "LGpgx787uvLeSdaPfu8qMQQIhsVFD7alvyYuQNrVmGG8I0RGvOAdd1BzXv7Y3aCV9ckCQ8lVCw9wMWP/wcceXFnvAezbgVObkm7YUwNairsJR+3LPI+80B4XxCgYT0V29Ak3YlEXxwBpWSG1US/l+yUxn1qcr3DGRCku4ghDh/g="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "samuelfpereira/travisCoverity"
      description: "coverity"
    notification_email: a81408@alunos.uminho.pt
    build_command_prepend:
    build_command: make
    branch_pattern: cov
script:
  - gcc main.c -o main
